-- SQL Schema for Pico Market (Pico House)
-- Execute this in your Supabase SQL Editor

-- 1. Products Table
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category TEXT NOT NULL, -- 'insta', 'tele', 'other'
  title TEXT NOT NULL,
  price TEXT NOT NULL,
  quality TEXT,
  image_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Winners Table
CREATE TABLE IF NOT EXISTS winners (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  prize TEXT NOT NULL,
  date TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Prizes Table
CREATE TABLE IF NOT EXISTS prizes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  amount TEXT NOT NULL,
  icon_code INTEGER NOT NULL,
  color_value INTEGER NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Lottery Participants Table
CREATE TABLE IF NOT EXISTS participants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  telegram TEXT NOT NULL,
  date TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Orders Table
CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_name TEXT NOT NULL,
  user_phone TEXT NOT NULL,
  product_title TEXT NOT NULL,
  page_id TEXT NOT NULL,
  quantity TEXT NOT NULL,
  request_details TEXT,
  status TEXT DEFAULT 'در انتظار بررسی',
  date TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. App Config Table
CREATE TABLE IF NOT EXISTS app_config (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT UNIQUE NOT NULL,
  value TEXT NOT NULL
);

-- Seed Initial Config Data
INSERT INTO app_config (key, value) VALUES
('lottery_banner_title', 'قرعه‌کشی بزرگ هفتگی پیکو مارکت'),
('lottery_banner_prize', 'جایزه ویژه: ۵ میلیون تومان وجه نقد'),
('lottery_banner_date', 'جمعه ساعت ۲۱:۰۰'),
('insta_id', 'pico_market_app'),
('telegram_id', '@pico_support'),
('support_email', 'support@pico.ir')
ON CONFLICT (key) DO NOTHING;
